### ISSUE TITLE
Option to not show 'logout' modal dialog immediately after the login

### ISSUE THREAD

**Issue by KrishnaPG** [netlify/netlify-identity-widget#132] opened 2018-04-21 04:02 UTC
Currently, after successful login, a modal dialog is shown with "logout" button immediately.

User has to dismiss that "logout" modal dialog before he can proceed with further action.

Is it possible to turn off that 'logout' modal display after login? It is confusing to the most users. 

How to configure this 'logout' to not display?

**Comment by bcomnes** [comment] 2018-04-23 23:12
Duplicate of https://github.com/netlify/netlify-identity-widget/issues/85 so lets close that and move discussion over there.  Apologies for the slow movement on this recently.  I'm triaging a bunch of issues to get them into upcoming sprints.

**Closed by bcomnes** 2018-04-23 23:12 UTC
