### ISSUE TITLE
Improve misleading pop-up login

### ISSUE THREAD

**Issue by idiazroncero** [netlify/netlify-identity-widget#183] opened 2019-04-21 18:59 UTC
Hello;

( This issue was originally posed on netlify-cms repo, on https://github.com/netlify/netlify-cms/issues/2031 )

I always found the UI design of **the "user" modal that appears immediately after logging in**  clearly misleading to the end-user:

<img width="389" alt="captura de pantalla 2019-01-25 a las 12 18 10" src="https://user-images.githubusercontent.com/3958741/51742979-972f7400-209b-11e9-9889-3e5449f51f19.png">

I have myself countless times clicked on the "log out" button by impulse. I think this is clearly a bad UI for the following reasons:

- Buttons doesn't give any visual clue of wether they lead to a 'positive' action (i.e.: log in, recover password, yes, continue) or 'negative' (i.e: log out, cancel, back)
- The negative "log out" button appears on the same color, same size and same position than the previous, positive "log in" button.
- There is no other action than "log out" on this modal. To successfully proceed to the admin section, you have to close the modal. The only action that's cleary available on the pop up is the **exact opposite** of what the user might want to do!!

**Proposed solution**

The welcome pop-up (and the whole login) should at least provide the following:
- Visual clues (icons, colors) on wheter the action is considered "positive" (leading towards the goal of login in) or "negative".
- An alternate, bigger "continue" button that closes the pop up and proceeds to the admin section (which is the direction that most users want to take!)

Something like this (but well-designed, of course!)

![diffui](https://user-images.githubusercontent.com/3958741/51743641-9b5c9100-209d-11e9-923a-e3e96ec6e2c1.jpg)

**Describe alternatives you've considered**

Another solution, even clearer, might be to just redirect the user to the administration without any popup. I don't find of any use to present the user the option of logging out just a few milliseconds _after_ logging in.

**Comment by idiazroncero** [comment] 2019-04-24 08:15
Just to be clear: 

The log out modal is just fine. The problem is its appearance just before login. I think we should either create a new type of modal or delete it.

**Comment by jlengstorf** [comment] 2020-07-30 01:07
this is a duplicate of https://github.com/netlify/netlify-identity-widget/issues/85 — I'm going to close this to consolidate the issues, but we're still tracking this feature request!

**Closed by jlengstorf** 2020-07-30 01:07 UTC
Labels: enhancement, feature request
