### ISSUE TITLE
Development Settings section showing in production

### ISSUE THREAD

**Issue by BrandonNoad** [netlify/netlify-identity-widget#188] opened 2019-05-29 03:09 UTC
After upgrading from v1.5.2 to v1.5.4, the "Development Settings" section is showing, even when deployed to production (see screenshot):

![https___blissful-swartz-fbf974_netlify_com](https://user-images.githubusercontent.com/1979809/58526481-172a2f80-819d-11e9-96e7-8008c412088b.png)

Is there something I need to configure to disable development mode?

Thanks.

**Comment by sw-yx** [comment] 2019-05-29 03:30
thanks for filing an issue. this seems like an accidental regression. cc @shortdiv https://github.com/netlify/netlify-identity-widget/commit/bfe5e8f0c849e0ef713c51e8566f6127728227c6

**Comment by neekey** [comment] 2019-05-31 12:00
I have the same issue as well, as the invitation workflow does not work, after click the address from the email, i get back to my production url but only see the same login in form pop up

**Comment by neekey** [comment] 2019-05-31 14:33
roll back to `v1.5.2` works for me.

Still I encountered an issue that none of the invitation and reset password workflow worked for me. After I clicked the link in my email, i always get back to my site and showing the login form.

I spent several hours debugging into the code, and I found the cause, which technically is my fault:

- I manually called the `open()` function in the main component of my app after it finished mount.
- when the Netlify Identify Widget detected the current hash and marked as "invite" or "reset_password", then because my manual call of `open()` it overrided the `store.modal.page` to `login`, as without given any `action` to `open()` that's the default action.

Which caused my issue.

My solution is just get rid of the manual call of `open()` and works well.

So should we handle this conflict better, for example, if no action is specified, only set the `page` to `login` if currently there's no `page` set?

**Comment by sw-yx** [comment] 2019-05-31 17:26
thanks for the extensive report! will leave it to @shortdiv. but yea part of the tradeoff of getting this nice UI is that we have to make some decisions for you. can always fork or drop down to `gotrue-js` if you really need to.

**Comment by BrandonNoad** [comment] 2019-05-31 20:20
@neekey you could probably just do:

```
if (window.location.hash === '') {
    netlifyIdentity.open();
}
```

**Comment by jlengstorf** [comment] 2020-07-30 00:28
this has been fixed. if anyone sees this issue again, please open a new issue! thanks!

**Closed by jlengstorf** 2020-07-30 00:28 UTC
